//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CUS
    {
        public int ID { get; set; }
        public string Sup_Name { get; set; }
        public string Sup_Phone { get; set; }
        public string Sup_Email { get; set; }
        public byte[] Sup_image { get; set; }
    }
}
