using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using SMP.EPL;

namespace SMP.PL
{
    public partial class FRM_CAT : Form
    {
        DB_SMPEntities db = new SMP.DB_SMPEntities();
        TB_CAT tb_cat = new TB_CAT();
        BL.Methods methods = new BL.Methods();

        int id;
        public FRM_CAT()
        {


            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            SMP.DB_SMPEntities dbContext = new SMP.DB_SMPEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_CAT.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TB_CAT.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void btn_add_Click(object sender, EventArgs e)
        {
            PL.FRM_CAT_ADD frm_add = new FRM_CAT_ADD();
            frm_add.id = 0;
            frm_add.btn_add.Text = "اضافة";
            frm_add.Show();
        }

        private void btn_update_Click(object sender, EventArgs e)
        {
            update_data();

        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            Toast toast = new Toast();
            Dialog dialog = new Dialog();
            try
            {
                id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("ID"));
                var rs = MessageBox.Show("عملية حذف", "هل انت متاكد من هذه العملية", MessageBoxButtons.YesNo);
                if (rs == DialogResult.Yes)
                {

                    tb_cat = db.TB_CAT.Where(x => x.ID == id).FirstOrDefault();
                    db.Entry(tb_cat).State = EntityState.Deleted;
                    db.SaveChanges();
                    toast.txt_caption.Text = "تم حذف الصنف";
                    toast.Show();
                    update_data();
                }
            }
            catch
            {
                dialog.txt_caption.Text = "لا يوجد صنف لحذفه";
                dialog.Width = this.Width;
                dialog.Show();
            }


        }

        private void update_data()
        {
            db = new DB_SMPEntities();
            gridControl1.DataSource = db.TB_CAT.ToList();
        }
        //edit
        private void btn_edit_Click(object sender, EventArgs e)
        {
            PL.FRM_CAT_ADD frm_add = new FRM_CAT_ADD();
            id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("ID"));
            tb_cat = db.TB_CAT.Where(x => x.ID == id).FirstOrDefault();
            frm_add.edt_name.Text = tb_cat.CAT_Name.ToString();
            methods.by = tb_cat.CAT_Cover;
            frm_add.pic_cover.Image = Image.FromStream(methods.convert_image());

            frm_add.id = id;
            frm_add.btn_add.Text = "تعديل";
            frm_add.Show();
        }

        private void btn_search_Click(object sender, EventArgs e)
        {
            var _search = edit_search.Text;
            gridControl1.DataSource = db.TB_CAT.Where(x => x.CAT_Name.Contains(_search)).ToList();
        }
    }
}
