using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using SMP.EPL;

namespace SMP.PL
{
    public partial class FRM_PUR : Form
    {
        DB_SMPEntities db = new SMP.DB_SMPEntities();
        TB_PUR tb_pur = new TB_PUR();
        BL.Methods methods = new BL.Methods();

        int id;
        public FRM_PUR()
        {


            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            SMP.DB_SMPEntities dbContext = new SMP.DB_SMPEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_PUR.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TB_PUR.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }



        private void btn_add_Click(object sender, EventArgs e)
        {
            PL.FRM_PUR_ADD frm_add = new FRM_PUR_ADD();
            frm_add.id = 0;
            frm_add.btn_add.Text = "اضافة";
            frm_add.Show();
        }

        private void btn_update_Click(object sender, EventArgs e)
        {
            update_data();

        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            Toast toast = new Toast();
            Dialog dialog = new Dialog();
            id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
            if (id > 0)
            {
                try
                {
                    var rs = MessageBox.Show("عملية حذف", "هل انت متاكد من هذه العملية", MessageBoxButtons.YesNo);
                    if (rs == DialogResult.Yes)
                    {
                        tb_pur = db.TB_PUR.Where(x => x.ID == id).FirstOrDefault();
                        db.Entry(tb_pur).State = EntityState.Deleted;
                        db.SaveChanges();
                        toast.txt_caption.Text = "تم حذف عملية الشراء";
                        toast.Show();
                        update_data();
                    }
                }
                catch
                {

                }
            }
            else
            {
                dialog.txt_caption.Text = "لا توجد عملية لحذفها";
                dialog.Width = this.Width;
                dialog.Show();
            }



        }

        private void update_data()
        {
            db = new DB_SMPEntities();
            gridControl1.DataSource = db.TB_PUR.ToList();
        }
        //edit
        private void btn_edit_Click(object sender, EventArgs e)
        {
            PL.FRM_PUR_ADD frm_add = new FRM_PUR_ADD();
            id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
            tb_pur = db.TB_PUR.Where(x => x.ID == id).FirstOrDefault();
            frm_add.edt_name.Text = tb_pur.Pur_Name;
            frm_add.edt_type.Text = tb_pur.Pur_Type;
            frm_add.edt_cat.Text = tb_pur.Pur_Cat;
            frm_add.edt_sup.Text = tb_pur.Pur_Sup;
            frm_add.edt_det.Text = tb_pur.Pur_Det;
            frm_add.edt_buy.Text = tb_pur.Pur_Buy.ToString();
            frm_add.edt_sell.Text = tb_pur.Pur_Sell.ToString();
            frm_add.edt_qt.Text = tb_pur.Pur_Qt.ToString();
            frm_add.edt_tsell.Text = tb_pur.Pur_Tsell.ToString();
            frm_add.edt_tbuy.Text = tb_pur.Pur_Tbuy.ToString();
            frm_add.edt_trev.Text = tb_pur.Pur_TRev.ToString();
            frm_add.id = id;
            frm_add.btn_add.Text = "تعديل";
            frm_add.Show();
        }

        private void btn_search_Click(object sender, EventArgs e)
        {
            var _search = edit_search.Text;
            gridControl1.DataSource = db.TB_PUR.Where(x => x.Pur_Name.Contains(_search) || x.Pur_Type.Contains(_search) || x.Pur_Cat.Contains(_search)).ToList();
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }
    }
}
